name: Upload Photos and HTML

on:
  push:
    branches:
      - main # Change this to your default branch if not 'main'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Upload Vendor Photos
        if: github.event.inputs.image_type == 'vendor_img'
        uses: actions/upload-artifact@v2
        with:
          name: vendor-photos
          path: vendorpage/img_vendor/vendorpage_${{ github.event.inputs.vendor_name }}/vendor_img/*.*

      - name: Upload Menu Photos
        if: github.event.inputs.image_type == 'menu_img'
        uses: actions/upload-artifact@v2
        with:
          name: menu-photos
          path: vendorpage/img_vendor/vendorpage_${{ github.event.inputs.vendor_name }}/menu_img/*.*

      - name: Upload HTML Files
        uses: actions/upload-artifact@v2
        with:
          name: html
          path: vendorpage/${{ github.event.inputs.vendor_name }}.html
