# .github/workflows/main.yml

on:
  push:
    branches:
      - main

jobs:
  update_images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add and commit new images
      run: |
        git add -A
        git commit -m "Add new images"
        git push
